Implement SwingBrowserView
TeamDev-IP/Compose-BrowserView pull request #9
Opened 2023-02-17 13:43 UTC by Danil-Didkovskiy

Fixes #8 

In this changeset, we implement the `SwingBrowserView` component that embeds our `com.teamdev.jxbrowser.view.swing.BrowserView` in a Compose `SwingPanel`. 

We tested how our Swing `BrowserView` component behaves in the Compose environment. It supports all the necessary functionality, but we found one obvious problem - if it is embedded in `SwingPanel`, it is always heavyweight (regardless of the rendering mode). The [Swing integration](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Swing_Integration) in Compose only works in that way. Therefore, we decided to keep both implementations for now.

2023-02-17 13:46 UTC, Danil-Didkovskiy commented
@vladimir-ikryanov PTAL

2023-02-20 08:49 UTC, vladimir-ikryanov commented
@Danil-Didkovskiy Please fill in the following required PR fields:

- Reviewers
- Assignees (it's you)

2023-02-20 08:51 UTC, vladimir-ikryanov commented
@Danil-Didkovskiy I think we shouldn't mix both implementations in a single file. There's should be some hierarchy like:

```
             BrowserView
             |       |
ComposeBrowserView SwingBrowserView
```

2023-02-20 11:48 UTC, vladimir-ikryanov approved these changes

2023-02-20 11:48 UTC, vladimir-ikryanov requested changes

2023-02-20 11:48 UTC, vladimir-ikryanov commented on src/main/kotlin/com/teamdev/jxbrowser/compose/BrowserView.kt
> + * it adds the [ComposeBrowserView] component built with Compose only. On [HARDWARE_ACCELERATED],
Please don't share the implementation details in Javadoc.

2023-02-20 12:09 UTC, vladimir-ikryanov approved these changes

2023-02-20 12:23 UTC, merged